services:
  # Database Service
  db:
    image: mysql
    container_name: checkeapp-db-prod
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - ./.env 
    environment:
      DB_PASSWORD_ROOT: ${DB_PASSWORD_ROOT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - checkeapp_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - checkeapp-net

  # Backend Service
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: checkeapp-server-prod
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./apps/server/.env
    networks:
      - checkeapp-net

  # Frontend Service
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: checkeapp-web-prod
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3001:3001"
    env_file:
      - ./apps/web/.env
    networks:
      - checkeapp-net

volumes:
  checkeapp_db_data:

networks:
  checkeapp-net:
    driver: bridge
